<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class tbt_Payslip extends Model
{
    use HasFactory;
    protected $table = 'tbt_Payslip';
    protected $primaryKey = ['EmpCode', 'OrgUnitCode', 'PayDate'];
    protected $keyType = 'string';
    public $incrementing = false;
    protected $fillable = [
        'EmpCode',
        'EmpName',
        'EmpNameEng',
        'EmpType',
        'PositionCode',
        'PositionName',
        'PositionNameEng',
        'OrgUnitCode',
        'OrgUnitName',
        'OrgUnitNameEng',
        'ParentOrgUnitCode',
        'ParentOrgUnitName',
        'ParentOrgUnitNameEng',
        'PayDate',
        'StartDateTemplate',
        'PeriodDay',
        'Salary',
        'TotalIncome',
        'TotalDeduct',
        'ProvidentFund',
        'Social',
        'Organizer',
        'OrganizerEng',
        'Auditor',
        'AuditorEng',
        'Approver',
        'ApproverEng',
        'CheckAssociates',
        'EmpPaytax',
        'NetIncome',
        'EmployerPayTax',
        'CalcTaxType',
        'EmpType1',
        'PayPerMonth',
        'PeriodStartDate',
        'PeriodEndDate',
        'DayPerMonthDaily',
        'ResignInMonth',
        'ResignDate',
        'StartInMonth',
        'StartDate',
        'DayPerMonth',
        'TimeWork',
        'Daynum',
        'Income1',
        'Income2',
        'Income3',
        'Income4',
        'Income5',
        'Income6',
        'Income7',
        'Income8',
        'Income9',
        'Income10',
        'Income11',
        'Income12',
        'Income13',
        'Income14',
        'Income15',
        'Income16',
        'Income17',
        'Income18',
        'Income19',
        'Income20',
        'Deduct1',
        'Deduct2',
        'Deduct3',
        'Deduct4',
        'Deduct5',
        'Deduct6',
        'Deduct7',
        'Deduct8',
        'Deduct9',
        'Deduct10',
        'Deduct11',
        'Deduct12',
        'Deduct13',
        'Deduct14',
        'Deduct15',
        'Deduct16',
        'Deduct17',
        'Deduct18',
        'Deduct19',
        'Deduct20',
        'OtherIncome',
        'OtherDeduct',
        'EffectDate',
        'WorkStartDate',
        'WorkPeriodDay',
        'ResignWorkDate',
        'AmountDateBetPeriod',
        'WorkDayAll',
        'CalcIncomeOccasionalAt',
        'BaseSalary',
        'isActive',
        'printStatus'
    ];
}
